app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from app import settings
from main import views 
from goods import views
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls',namespace='main')),
    path('catalog/',include('goods.urls',namespace='goods'))
    

]

if settings.DEBUG:
    urlpatterns += [ path('debug/', include('debug_toolbar.urls')),

    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

goods/urls.py
from django.contrib import admin
from django.urls import path
from goods import views 

app_name = 'goods'
urlpatterns = [
    
    path('',views.catalog,name='index'),
    path('product/<slug:product_slug>/',views.product,name='product')
    ]

main/urls.py
from django.contrib import admin
from django.urls import path
import app
from main import views 

app_name = 'main'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('about/',views.about,name='about'),

]

goods/models.py
from email.mime import image
from django.db import models


class Categories(models.Model):
    name = models.CharField(
        max_length=150, unique=True, verbose_name="Название категории"
    )
    slug = models.SlugField(
        max_length=250, unique=True, blank=True, null=True, verbose_name="URL категории"
    )

    class Meta:
        db_table = "category"
        verbose_name = "Категорію"
        verbose_name_plural = "Категорії"

    def __str__(self):
        return self.name


class Products(models.Model):
    name = models.CharField(
        max_length=150, unique=True, verbose_name="Назва товару"
    )
    slug = models.SlugField(
        max_length=250, unique=True, blank=True, null=True, verbose_name="URL товару"
    )
    description = models.TextField(blank=True, null=True, verbose_name="Опис")
    img = models.ImageField(
        upload_to="goods_images", blank=True, null=True, verbose_name="Зображення"
    )
    price = models.DecimalField(
        default=0.00, max_digits=6, decimal_places=2, verbose_name="Ціна"
    )
    discount = models.DecimalField(
        default=0, max_digits=4, decimal_places=2, verbose_name="Скидка"
    )
    quantity = models.PositiveIntegerField(default=0, verbose_name="Кількість")
    category = models.ForeignKey(
        to=Categories, on_delete=models.CASCADE, verbose_name="Категорія"
    )

    class Meta:
        db_table = "products"
        verbose_name = "Товар"
        verbose_name_plural = "Товари"

    def __str__(self):
        return self.name
    
    def show_id(self):
        return f"{self.id:05}"
    
    def end_price(self):
        if self.discount:
            return round(self.price * (1-self.discount/100),2)
        return self.price

main/models.py
from django.db import models

# Create your models here.

goods/views.py
from django.shortcuts import render

from goods.models import Categories, Products


def catalog(request):


    products=Products.objects.all()

    

    context = {
        "title": "Каталог товаров",
        "categories": Categories.objects.all(),
        "products": products,
        
    }
    return render(request, "goods/catalog.html", context)


def product(request,product_slug):

    product=Products.objects.get(slug=product_slug)
    context = {
        
        "product": product,
       
    }
    return render(request, "goods/product.html", context)

main/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.template import context
from django.urls import path

from goods.models import Categories


def index(request):

    

    context = {
        "title": "Euggen-Shop",
        "content": "Магазин одягу EUGGEN",
        
        
        }

    return render(request, "main/index.html", context)


def about(request):

    context = {
        "title": "Euggen-Shop Про нас",
        "content": "Про нас",
        "text_on_page": "Дуже класний у нас інтернет магазин!....",
    }

    return render(request, "main/about.html", context)

goods/templates/goods/catalog.html
{% extends "main/base.html" %}
{% load static %}


{% block content %}

                   <!-- Контент на странице -->
                   <div class="row">
                    <!-- Форма фильтров -->
                    <div class="dropdown mb-2">
                        <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            Фильтры
                        </button>
                
                        <form action="" method="get" class="dropdown-menu bg-dark" data-bs-theme="dark">
                            <div class="form-check text-white mx-3">
                                <input class="form-check-input" type="checkbox" name="on_sale" id="flexCheckDefault" value="on">
                                <input type="hidden" name="q" value="request.GET.q">
                                <label class="form-check-label" for="flexCheckDefault">
                                    Товары по акции
                                </label>
                            </div>
                            <p class="text-white mx-3 mt-3">Сортировать:</p>
                            <div class="form-check text-white mx-3">
                                <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault1" value="default" checked>
                                <label class="form-check-label" for="flexRadioDefault1">
                                    По умолчанию
                                </label>
                            </div>
                            <div class="form-check text-white mx-3">
                                <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault2" value="price">
                                <label class="form-check-label" for="flexRadioDefault2">
                                    От дешевых к дорогим
                                </label>
                            </div>
                            <div class="form-check text-white mx-3">
                                <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault3" value="-price">
                                <label class="form-check-label" for="flexRadioDefault3">
                                    От дорогих к дешевым
                                </label>
                            </div>
                            <button type="submit" class="btn btn-primary mx-3 mt-3">Применить</button>
                        </form>
                    </div>


 {% for prod in products  %}
 
                   
                    <!-- Карта товара -->
                    <div class="col-lg-4 col-md-6 p-4">
                        <div class="card border-primary rounded custom-shadow">

                            {% if prod.img %}                           
                                <img src="{{prod.img.url}}" class="card-img-top" alt="{{prod.name}}">
                            {% else %}
                                <img src="{% static "deps/images/Not found image.png" %}" class="card-img-top" alt="...">
                            {% endif %}
                            
                            <div class="card-body">
                                <a href="{% url "goods:product" prod.slug %}"> 
                                    <p class="card-title">{{ prod.name }}</p>
                                </a>
                                <p class="card-text text-truncate">{{ prod.description }} </p>
                                <p class="product_id">id - {{prod.show_id}}</p>
                                <div class="d-flex justify-content-between">
                                    {% if prod.discount  %}
                                        <p><s>{{prod.price}}</s> гр</p>
                                        <p><strong>{{ prod.end_price }} гр</strong></p>
                                        <span class="badge bg-warning text-dark">Знижка {{ prod.discount }} %</span> 
                                    {% else %}
                                        <p><strong>{{ prod.price }}гр</strong></p>
                                    {% endif %}
                                    

                                    

                                    <a href="#" class="btn add-to-cart">
                                        <img class="mx-1" src="{% static "deps/icons/cart-plus.svg" %}" alt="Catalog Icon"
                                            width="32" height="32">
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
 {% endfor %}                   


                </div>
                <!-- Пагинация -->
                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center my-4">
                        <div class="custom-shadow d-flex">
                            <li class="page-item disabled">
                              <a class="page-link">Previous</a>
                            </li>
                            <li class="page-item"><a class="page-link" href="#">1</a></li>
                            <li class="page-item"><a class="page-link" href="#">2</a></li>
                            <li class="page-item"><a class="page-link" href="#">3</a></li>
                            <li class="page-item">
                              <a class="page-link" href="#">Next</a>
                            </li>
                        </div>
                    </ul>
                </nav>
{% endblock %}








goods/templates/goods/product.html
{% extends "main/base.html" %}
{% load static %}

{% block content %}
       <!-- Контент -->
        <div class="container">
            <div class="row mt-1">
                <div class="col-lg-2">
                    <!-- Пустой блок на усмотрение -->
                </div>
                <div class="col-lg-10">
                    <!-- Контент на странице -->
                    <div class="container mt-5">
                        <div class="card mb-4 custom-shadow">
                            <div class="row">
                                <!-- Миниатюры -->
                                <div class="col-md-4">
                                    <img src="{{ product.img.url }}" 
                                        class="img-thumbnail" data-bs-toggle="modal" data-bs-target="#imageModal1">
                                </div>
                                <div class="col-md-4 ">
                                    <p class="product_id mt-3">id:{{product.show_id}}</p>
                                </div>
                                <!-- Увеличить изображение в модальном окне -->
                                <div class="modal fade" id="imageModal1" tabindex="-1"
                                    aria-labelledby="imageModal1Label" aria-hidden="true">
                                    <div class="modal-dialog modal-lg">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="imageModal1Label">{{product.name}} </h5>
                                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                    aria-label="Закрыть"></button>
                                            </div>
                                            <div class="modal-body">
                                                <img src="{{ product.img.url }}"
                                                    class="img-fluid" alt="Изображение 1">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- Описание товара -->
                            <div class="card-body">
                                <p class="card-text">Цена: <strong>{{product.end_price}} гр</strong></p>
                                <h5 class="card-title">{{ product.name }}</h5>
                                <p class="card-text">{{ product.description }}</p>
                                <a href="#" class="btn btn-dark add-to-cart">Добавить в корзину</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

main/templates/main/about.html

{% extends "main/base.html" %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static "deps/css/my_footer_css.css" %}">
{% endblock  %}



{% block content %}
    <div class="mt-5 pt-5 bg-white custom-shadow">
        
        <h2 ><strong>{{ content }}</strong></h2>
        <p>{{ text_on_page }}</p>

    </div>
{% endblock %}

{% block footer %}
    <footer class="py-4 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Made by Eugen Yaniv

            </p>
        </div>
    </footer>
{% endblock %}



main/templates/main/base.html
{% load static %}
{% load goods_tags %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "deps/css/bootstrap/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "deps/css/my_css.css" %}">
    <!-- Стиль footer-a для главной страницы -->
    {% block css %}
    {% endblock  %}
    <!-- Favicons for different platforms -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static "deps/favicon/apple-touch-icon.png" %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static "deps/favicon/favicon-32x32.png" %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static "deps/favicon/favicon-16x16.png" %}">
    <link rel="manifest" href="{% static "deps/favicon/site.webmanifest" %}">
    <title>{{ title }}</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
            <div class="container">
                <a class="navbar-brand" href="{% url "main:index" %}">Euggen</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item dropdown ">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Інформація
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item  text-white" href="#">Доставка та оплата</a></li>
                                <li><a class="dropdown-item  text-white" href="#">Контактна інформація</a></li>
                                <li><a class="dropdown-item  text-white" href="{% url "main:about" %}">Про нас</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link  text-white" href="carts/cart.html">Корзина</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link  text-white" href="users/login.html">Увійти</a>
                        </li>
                        <li class="nav-item dropdown ">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Мій профіль
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item  text-white" href="carts/cart.html">Корзина</a></li>
                                <li><a class="dropdown-item  text-white" href="users/profile.html">Особист. кабінет</a>
                                </li>
                                <li><a class="dropdown-item  text-white" href="{% url "admin:index" %}">Адмін панель</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item  text-white" href="#">Вийти</a></li>
                            </ul>
                        </li>
                    </ul>
                    <form class="d-flex" role="search">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success text-white" type="submit">Пошук</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <section>
        <div class="container">
            <!-- Каталог и корзина с фиксированным расположением на странице -->
            <div class="row mt-1 position-fixed z-3">
                <!-- Каталог -->
                <div class="dropdown mb-2">
                    <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Каталог
                        <img class="mx-1" src="{% static "deps/icons/grid-fill.svg" %}" alt="Catalog Icon" width="16"
                            height="16">
                    </button>
                    <ul class="dropdown-menu bg-dark" data-bs-theme="dark">
                        {% tag_categories as categories %}
                        {% for cat in categories %}
                            <li><a class="dropdown-item text-white" href="{% url "goods:index" %}">{{ cat.name }}</a></li>             
                        {% endfor %}


                    </ul>
                </div>
                <!-- Значек корзины, вызывает модальное окно -->
                <div>
                    <button type="button" class="btn btn-dark btn-secondary d-flex" id="modalButton"
                        aria-expanded="false">
                        <img class="mx-1" src="{% static "deps/icons/basket2-fill.svg" %}" alt="Catalog Icon" width="24"
                            height="24">
                        <span id="goods-in-cart-count">0</span>
                    </button>
                </div>
                <!-- Разметка модального окна корзины -->
                <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                    aria-hidden="true">
                    <div class="modal-dialog modal-dialog-scrollable">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                    aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <h3 class="text-center mb-4">Корзина</h3>
                                <div class="container" id="cart-items-container">
                                    <!-- Разметка корзины -->
                                    <div class="card mb-3 text-bg-light shadow-lg">
                                        <div class="card-header">
                                            <h5 class="card-title">Товар</h5>
                                        </div>
                                        <ul class="list-group list-group-flush">
                                            <li class="list-group-item">
                                                <div class="row text-center">
                                                    <div class="col p-0">
                                                        <div class="input-group">
                                                            <span class="input-group-btn">
                                                                <button type="button" class="btn btn-dark btn-sm decrement"
                                                                    data-cart-id="" data-cart-change-url="">-</button>
                                                            </span>
                                                            <input type="text" class="form-control number" value="1"
                                                                readonly>
                                                            <span class="input-group-btn">
                                                                <button type="button" class="btn btn-dark btn-sm increment"
                                                                    data-cart-id="" data-cart-change-url="">+</button>
                                                            </span>
                                                        </div>
                                                    </div>
                                                    <div class="col p-0">
                                                        <p>x 100.00 = </p>
                                                    </div>
                                                    <div class="col p-0"><strong>100.00 гр</strong></div>
                                                    <div class="col p-0">
                                                        <a href="#" class="remove-from-cart" data-cart-id="">
                                                            <img class="mx-1" src="{% static "deps/icons/trash3-fill.svg" %}"
                                                                alt="Catalog Icon" width="16" height="16">
                                                        </a>
                                                    </div>
                                                </div>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="card mb-3 shadow-lg">
                                        <div class="card-footer">
                                            <p class="float-left">Итого <strong>1</strong> товар(ів) на сумму</p>
                                            <h4 class="float-left"><strong>100.00 гр</strong></h4>
                                        </div>
                                    </div>
                                    <!-- Закончилась разметка корзины -->
                                </div>
                                <a class="btn btn-dark" href="orders/create_order.html">
                                    Оформити заказ
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Закончилась разметка модального окна -->
            </div>
        </div>
        <!-- Контент -->
        <div class="container">
            <div class="row mt-1">
                <div class="col-lg-2">
                    <!-- Пустой блок на Ваше усмотрение -->
                </div>
                <div class="col-lg-10">
                    <!-- Контент на странице -->
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </section>
    {% block footer %}
    {% endblock %}
    <script src="{% static "deps/js/jquery/jquery-3.7.0.min.js" %}"></script>
    <script src="{% static "deps/js/jquery-events.js" %}"></script>
    <script src="{% static "deps/js/jquery-ajax.js" %}"></script>
    <script src="{% static "deps/js/bootstrap/bootstrap.bundle.min.js" %}"></script>
</body>

</html>

main/templates/main/index.html
{% extends "main/base.html" %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static "deps/css/my_footer_css.css" %}">
{% endblock  %}



{% block content %}
    <h1 class="mt-5 pt-5"><strong>{{ content }}</strong></h1>
{% endblock %}

{% block footer %}
    <footer class="py-4 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Made by Eugen Yaniv

            </p>
        </div>
    </footer>
{% endblock %}



